import type { Metadata } from "next";
import { Geist, Geist_Mono ,Marcellus,Inter ,Playfair_Display ,Poppins} from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/Footer";
import Navbar from "./components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const marcellus = Marcellus({
  weight: "400",               // REQUIRED
  subsets: ["latin"],
  variable: "--font-marcellus",
  display: "swap",
});;


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfairDisplay",
  display: "swap",
});
const poppins = Poppins({
  weight:"400",
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${marcellus.variable}  ${inter.variable} ${playfairDisplay.variable} ${poppins.variable}   antialiased`}
        > 
        <Navbar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
